# Generated by Django 5.2.12 on 2026-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="intro",
            field=models.CharField(default="", max_length=250),
        ),
    ]
