# Generated by Django 5.2.12 on 2026-03-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
