# Generated by Django 5.2.12 on 2026-04-01 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
